# coding=utf-8
from django.conf import settings

CONTENT_INTERACTIONS_STATS_PROCESSORS = getattr(settings, 'CONTENT_INTERACTIONS_STATS_PROCESSORS', (
    'content_interactions_stats.processors.Likes',
    'content_interactions_stats.processors.FavoriteMarks',
    'content_interactions_stats.processors.Shares',
    'content_interactions_stats.processors.Denounces',
    'content_interactions_stats.processors.Ratings',
    'content_interactions_stats.processors.Comments',
    'content_interactions_stats.processors.Visits',
))

CONTENT_INTERACTIONS_STATS_PROCESSING_DELAY = getattr(
    settings, 'CONTENT_INTERACTIONS_STATS_PROCESSING_DELAY', True
)
CONTENT_INTERACTIONS_LIKE_PROCESSING_DELAY = getattr(
    settings, 'CONTENT_INTERACTIONS_LIKE_PROCESSING_DELAY', CONTENT_INTERACTIONS_STATS_PROCESSING_DELAY
)
CONTENT_INTERACTIONS_RATE_PROCESSING_DELAY = getattr(
    settings, 'CONTENT_INTERACTIONS_RATE_PROCESSING_DELAY', CONTENT_INTERACTIONS_STATS_PROCESSING_DELAY
)
CONTENT_INTERACTIONS_FAVORITE_PROCESSING_DELAY = getattr(
    settings, 'CONTENT_INTERACTIONS_FAVORITE_PROCESSING_DELAY', CONTENT_INTERACTIONS_STATS_PROCESSING_DELAY
)
CONTENT_INTERACTIONS_DENOUNCE_PROCESSING_DELAY = getattr(
    settings, 'CONTENT_INTERACTIONS_DENOUNCE_PROCESSING_DELAY', CONTENT_INTERACTIONS_STATS_PROCESSING_DELAY
)
CONTENT_INTERACTIONS_SHARE_PROCESSING_DELAY = getattr(
    settings, 'CONTENT_INTERACTIONS_SHARE_PROCESSING_DELAY', CONTENT_INTERACTIONS_STATS_PROCESSING_DELAY
)
CONTENT_INTERACTIONS_COMMENT_PROCESSING_DELAY = getattr(
    settings, 'CONTENT_INTERACTIONS_COMMENT_PROCESSING_DELAY', CONTENT_INTERACTIONS_STATS_PROCESSING_DELAY
)
CONTENT_INTERACTIONS_VISIT_PROCESSING_DELAY = getattr(
    settings, 'CONTENT_INTERACTIONS_VISIT_PROCESSING_DELAY', CONTENT_INTERACTIONS_STATS_PROCESSING_DELAY
)